name = "DataWrangler"
uuid = "a7a6b7e4-f56f-4e7a-9983-6838d7ccc3b8"
authors = ["Fran Urbano <viraltux@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Smoothers = "012d725f-b4dd-4916-8440-03955fc52575"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
