name = "DataWrangler"
uuid = "a7a6b7e4-f56f-4e7a-9983-6838d7ccc3b8"
authors = ["Fran Urbano <viraltux@gmail.com> and contributors"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Smoothers = "012d725f-b4dd-4916-8440-03955fc52575"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Optim = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
